import { SampleRow, Attribute } from "../mockData";

export interface PasteResult {
  updatedRows?: SampleRow[];
  newRowsToImport?: Omit<SampleRow, "id">[];
  overrideStartRowId?: number;
  message?: string;
  severity?: "success" | "error" | "warning";
}

function getNextRowId(sourceRows: SampleRow[]): number {
  if (sourceRows.length === 0) return 1;
  const maxId = sourceRows.reduce(
    (max, row) => (Number.isFinite(row.id) && row.id > max ? row.id : max),
    Number.NEGATIVE_INFINITY,
  );
  return Number.isFinite(maxId) ? maxId + 1 : 1;
}

/**
 * RFC 4180 / TSV compliant parser:
 * - Parses tab-delimited values (TSV) where cells can be enclosed in double quotes ("...").
 * - Supports newlines (\r\n, \n, \r) inside quoted cells without treating them as row breaks.
 * - Supports escaped double quotes ("") inside quoted cells.
 * - Automatically normalizes inside-cell carriage returns (\r\n / \r -> \n).
 * - Strips trailing empty rows generated by Excel clipboard operations.
 */
export function parseTSV(text: string): string[][] {
  if (!text) return [];

  const rows: string[][] = [];
  let currentRow: string[] = [];
  let currentCell = "";
  let insideQuotes = false;
  let i = 0;
  const len = text.length;

  while (i < len) {
    const char = text[i];

    if (insideQuotes) {
      if (char === '"') {
        if (i + 1 < len && text[i + 1] === '"') {
          // Escaped quote: "" inside quotes becomes a single "
          currentCell += '"';
          i += 2;
          continue;
        } else {
          // Closing quote
          insideQuotes = false;
          i++;
          continue;
        }
      } else {
        // Any character inside quotes is literal
        currentCell += char;
        i++;
        continue;
      }
    } else {
      if (char === '"') {
        // Opening quote if at start of cell
        if (currentCell.length === 0) {
          insideQuotes = true;
          i++;
          continue;
        } else {
          currentCell += char;
          i++;
          continue;
        }
      } else if (char === "\t") {
        currentRow.push(currentCell);
        currentCell = "";
        i++;
        continue;
      } else if (char === "\r") {
        if (i + 1 < len && text[i + 1] === "\n") {
          i++;
        }
        currentRow.push(currentCell);
        currentCell = "";
        rows.push(currentRow);
        currentRow = [];
        i++;
        continue;
      } else if (char === "\n") {
        currentRow.push(currentCell);
        currentCell = "";
        rows.push(currentRow);
        currentRow = [];
        i++;
        continue;
      } else {
        currentCell += char;
        i++;
        continue;
      }
    }
  }

  // Push remainder
  if (currentCell.length > 0 || currentRow.length > 0) {
    currentRow.push(currentCell);
    rows.push(currentRow);
  }

  // Normalize newlines inside cells: \r\n and \r -> \n
  const normalizedRows = rows.map((row) =>
    row.map((cell) => cell.replace(/\r\n/g, "\n").replace(/\r/g, "\n"))
  );

  // Strip trailing empty row (Excel clipboard often ends with \r\n)
  while (
    normalizedRows.length > 0 &&
    (normalizedRows[normalizedRows.length - 1].length === 0 ||
      (normalizedRows[normalizedRows.length - 1].length === 1 &&
        normalizedRows[normalizedRows.length - 1][0] === ""))
  ) {
    normalizedRows.pop();
  }

  return normalizedRows;
}

/**
 * Filename validation regex:
 * - Base name cannot be empty and cannot contain forbidden characters: \ / : * ? " < > | \r \n \t
 * - Must contain a period followed by a file extension of 1 to 10 alphanumeric characters.
 */
export const FILENAME_REGEX = /^[^\\/:*?"<>|\r\n\t.]+(\.[^\\/:*?"<>|\r\n\t.]+)*\.[a-zA-Z0-9]{1,10}$/;

export function validateAndNormalizeResult(val: string): {
  isValid: boolean;
  normalized: "Pass" | "Fail";
  error?: string;
} {
  const trimmed = (val || "").trim();
  if (/^pass$/i.test(trimmed)) {
    return { isValid: true, normalized: "Pass" };
  }
  if (/^fail$/i.test(trimmed)) {
    return { isValid: true, normalized: "Fail" };
  }
  return {
    isValid: false,
    normalized: "Pass",
    error: `Invalid Result value: '${val}'. Only 'Pass' or 'Fail' are allowed.`,
  };
}

export function validateAndNormalizeEvidence(
  val: string,
  evidenceOptions: string[] = []
): {
  isValid: boolean;
  normalized: string;
  error?: string;
} {
  const trimmed = (val || "").trim();
  if (!trimmed) {
    return { isValid: true, normalized: "" };
  }

  // Split by semicolon, trim every part (removes spaces around semicolons and filenames)
  const parts = trimmed
    .split(";")
    .map((p) => p.trim())
    .filter((p) => p.length > 0);

  if (parts.length === 0) {
    return {
      isValid: false,
      normalized: "",
      error: `Evidence value is invalid.`,
    };
  }

  const optionSet = new Set(
    (evidenceOptions || []).map((opt) => opt.trim().toLowerCase()).filter(Boolean)
  );

  for (const part of parts) {
    const isMatchingOption = optionSet.has(part.toLowerCase());
    const isMatchingFilePattern = FILENAME_REGEX.test(part);

    if (!isMatchingOption && !isMatchingFilePattern) {
      return {
        isValid: false,
        normalized: "",
        error: `Invalid evidence filename format: '${part}'. Files must have a valid extension (e.g. .pdf, .png).`,
      };
    }
  }

  return {
    isValid: true,
    normalized: parts.join(";"),
  };
}

/**
 * Parses and processes TSV data pasted from the clipboard (e.g. Excel).
 * Pure function mirror of useTableData.ts's handleDirectPaste — no React
 * state, so it can be unit tested directly.
 */
export function processPaste(
  text: string,
  rows: SampleRow[],
  attributes: Attribute[],
  activeRowId: number | null,
  activeColumnId: string | null,
  evidenceOptions: string[] = [],
): PasteResult {
  if (!text) return {};

  const rawGrid = parseTSV(text);
  const grid: string[][] = rawGrid.map((row) => row.map((cell) => cell.trim()));

  while (
    grid.length > 0 &&
    (grid[grid.length - 1].length === 0 ||
      (grid[grid.length - 1].length === 1 && grid[grid.length - 1][0] === ""))
  ) {
    grid.pop();
  }

  if (grid.length === 0) return {};

  const columnOrder = ["week", ...attributes.map((a) => a.id), "evidence", "result", "comment"];
  const startRowIdx = activeRowId !== null ? rows.findIndex((r) => r.id === activeRowId) : -1;

  const targetColId =
    activeRowId !== null && (activeColumnId === null || activeColumnId === "order")
      ? "week"
      : activeColumnId;
  const startColIdx = targetColId !== null ? columnOrder.indexOf(targetColId) : -1;

  let adjustedGrid = grid;
  if (activeColumnId === "order" && grid.length > 0 && grid[0].length > 1) {
    const firstCell = grid[0][0].toLowerCase();
    const isFirstCellOrder = /^\d+$/.test(firstCell) || firstCell === "order" || firstCell === "id";
    if (isFirstCellOrder) {
      adjustedGrid = grid.map((row) => row.slice(1));
    }
  }

  // ---- Flexible cell-level paste (an active cell is selected) ----
  if (startRowIdx !== -1 && startColIdx !== -1) {
    const pastedRows = adjustedGrid.length;
    const pastedCols = Math.max(...adjustedGrid.map((r) => r.length));
    const remainingRows = rows.length - startRowIdx;
    const remainingCols = columnOrder.length - startColIdx;

    if (pastedRows > remainingRows || pastedCols > remainingCols) {
      return {
        message: "Cannot paste because content exceeds the available range.",
        severity: "error",
      };
    }

    const isMultiCell = adjustedGrid.length > 1 || adjustedGrid.some((row) => row.length > 1);

    if (!isMultiCell) {
      const targetVal = adjustedGrid[0][0];
      const currentTargetColId = columnOrder[startColIdx];

      if (currentTargetColId === "result") {
        const resCheck = validateAndNormalizeResult(targetVal);
        if (!resCheck.isValid) {
          return {
            message: resCheck.error,
            severity: "warning",
          };
        }
      } else if (currentTargetColId === "evidence") {
        const eviCheck = validateAndNormalizeEvidence(targetVal, evidenceOptions);
        if (!eviCheck.isValid) {
          return {
            message: eviCheck.error,
            severity: "warning",
          };
        }
      }

      const updatedRows = rows.map((row, idx) => {
        if (idx !== startRowIdx) return row;
        if (currentTargetColId === "week") {
          return { ...row, week: targetVal };
        } else if (currentTargetColId === "evidence") {
          const eviCheck = validateAndNormalizeEvidence(targetVal, evidenceOptions);
          return { ...row, evidence: eviCheck.normalized };
        } else if (currentTargetColId === "result") {
          const resCheck = validateAndNormalizeResult(targetVal);
          return { ...row, result: resCheck.normalized };
        } else if (currentTargetColId === "comment") {
          return { ...row, comment: targetVal };
        } else {
          let cleanVal = targetVal;
          if (/^pass$/i.test(cleanVal)) {
            cleanVal = "Pass";
          } else if (/^fail$/i.test(cleanVal)) {
            cleanVal = "Fail";
          }
          return {
            ...row,
            attributes: {
              ...row.attributes,
              [currentTargetColId]: cleanVal,
            },
          };
        }
      });

      return {
        updatedRows,
        message: "Successfully pasted value to the selected cell!",
        severity: "success",
      };
    } else {
      const updatedRows = [...rows];
      let nextId = getNextRowId(updatedRows);
      const warnings: string[] = [];

      adjustedGrid.forEach((gridRow, r) => {
        const targetRowIdx = startRowIdx + r;

        if (targetRowIdx >= updatedRows.length) {
          const defaultAttributes: Record<string, string> = {};
          attributes.forEach((attr) => {
            defaultAttributes[attr.id] = "";
          });
          updatedRows.push({
            id: nextId++,
            week: "",
            attributes: defaultAttributes,
            evidence: "",
            result: "Pass",
            comment: "",
          });
        }

        const rowToUpdate = { ...updatedRows[targetRowIdx] };
        rowToUpdate.attributes = { ...rowToUpdate.attributes };

        gridRow.forEach((cellVal, c) => {
          const innerTargetColIdx = startColIdx + c;
          if (innerTargetColIdx < columnOrder.length) {
            const colId = columnOrder[innerTargetColIdx];
            if (colId === "week") {
              rowToUpdate.week = cellVal;
            } else if (colId === "evidence") {
              const eviCheck = validateAndNormalizeEvidence(cellVal, evidenceOptions);
              if (eviCheck.isValid) {
                rowToUpdate.evidence = eviCheck.normalized;
              } else {
                warnings.push(`Row ${targetRowIdx + 1} Evidence: '${cellVal}' is invalid`);
              }
            } else if (colId === "result") {
              const resCheck = validateAndNormalizeResult(cellVal);
              if (resCheck.isValid) {
                rowToUpdate.result = resCheck.normalized;
              } else {
                warnings.push(`Row ${targetRowIdx + 1} Result: '${cellVal}' is invalid`);
              }
            } else if (colId === "comment") {
              rowToUpdate.comment = cellVal;
            } else {
              let cleanVal = cellVal;
              if (/^pass$/i.test(cellVal)) {
                cleanVal = "Pass";
              } else if (/^fail$/i.test(cellVal)) {
                cleanVal = "Fail";
              }
              rowToUpdate.attributes[colId] = cleanVal;
            }
          }
        });

        updatedRows[targetRowIdx] = rowToUpdate;
      });

      if (warnings.length > 0) {
        return {
          updatedRows,
          message: `Pasted with warnings: ${warnings.slice(0, 2).join("; ")}${warnings.length > 2 ? ` (+${warnings.length - 2} more)` : ""}`,
          severity: "warning",
        };
      }

      return {
        updatedRows,
        message: "Successfully pasted and overrode cell range starting from selected cell!",
        severity: "success",
      };
    }
  }

  // ---- FALLBACK TO ROW-LEVEL OVERRIDE BEHAVIOR ----
  const filteredGrid = grid.filter((row) => row.length > 0 && row.some((cell) => cell !== ""));
  if (filteredGrid.length === 0) return {};

  let dataStartIndex = 0;
  const firstRow = filteredGrid[0];
  const looksLikeHeader = firstRow.some((cell) => {
    const lower = cell.toLowerCase();
    return (
      lower.includes("week") ||
      lower.includes("order") ||
      lower.includes("evidence") ||
      lower.includes("result") ||
      lower.includes("attribute") ||
      lower.includes("comment")
    );
  });

  if (looksLikeHeader) {
    dataStartIndex = 1;
  }

  type ColumnMapping =
    | { type: "order" }
    | { type: "week" }
    | { type: "attribute"; attributeId: string }
    | { type: "evidence" }
    | { type: "result" }
    | { type: "comment" }
    | { type: "unknown" };

  const headerMappings: ColumnMapping[] = [];

  if (looksLikeHeader) {
    firstRow.forEach((cell) => {
      const lower = cell.toLowerCase();
      if (lower.includes("order") || lower === "id") {
        headerMappings.push({ type: "order" });
      } else if (lower.includes("week") || lower.includes("date") || lower.includes("sample w")) {
        headerMappings.push({ type: "week" });
      } else if (lower.includes("evidence") || lower.includes("support")) {
        headerMappings.push({ type: "evidence" });
      } else if (lower.includes("result") || lower.includes("assess") || lower.includes("pass/fail")) {
        headerMappings.push({ type: "result" });
      } else if (lower.includes("comment")) {
        headerMappings.push({ type: "comment" });
      } else {
        const matchedAttr = attributes.find((attr) => {
          const attrNameLower = attr.name.toLowerCase();
          return (
            lower === attrNameLower ||
            lower.includes(attrNameLower) ||
            lower.replace(/\s+/g, "").includes(attrNameLower.replace(/\s+/g, ""))
          );
        });

        if (matchedAttr) {
          headerMappings.push({ type: "attribute", attributeId: matchedAttr.id });
        } else {
          const match = lower.match(/attr(ibute)?\s*(\d+)/i);
          if (match) {
            const num = match[2];
            const matchedAttrByNum = attributes.find(
              (attr) =>
                attr.name.toLowerCase().includes(`attribute ${num}`) ||
                attr.name.toLowerCase().includes(`attr ${num}`),
            );
            if (matchedAttrByNum) {
              headerMappings.push({ type: "attribute", attributeId: matchedAttrByNum.id });
              return;
            }
          }
          headerMappings.push({ type: "unknown" });
        }
      }
    });
  }

  const newRowsData: Omit<SampleRow, "id">[] = [];
  const rowWarnings: string[] = [];

  for (let i = dataStartIndex; i < filteredGrid.length; i++) {
    const cells = filteredGrid[i];
    if (cells.length < 3) continue;

    let rowMappings = headerMappings;

    if (!looksLikeHeader) {
      // Tổng số cột kỳ vọng: week + attributes + evidence + result + comment
      const expectedColsWithoutOrder = 1 + attributes.length + 3;
      const expectedColsWithOrder = expectedColsWithoutOrder + 1;

      let hasIdColumn = false;
      if (cells.length === expectedColsWithOrder && /^\d+$/.test(cells[0])) {
        hasIdColumn = true;
      } else if (cells.length === expectedColsWithoutOrder) {
        hasIdColumn = false;
      } else if (cells.length >= 5 && /^\d+$/.test(cells[0])) {
        // Không khớp số cột kỳ vọng nào -> fallback về cách đoán cũ
        const secondCellLower = cells[1].toLowerCase();
        const isSecondCellAttribute =
          secondCellLower === "pass" ||
          secondCellLower === "fail" ||
          secondCellLower === "n/a" ||
          secondCellLower === "";
        if (!isSecondCellAttribute) {
          hasIdColumn = true;
        }
      }

      const colOffset = hasIdColumn ? 1 : 0;
      rowMappings = [];
      if (hasIdColumn) rowMappings.push({ type: "order" });
      rowMappings.push({ type: "week" });

      const pastedAttrCount = cells.length - (colOffset + 1 + 3);
      for (let idx = 0; idx < pastedAttrCount; idx++) {
        if (idx < attributes.length) {
          rowMappings.push({ type: "attribute", attributeId: attributes[idx].id });
        } else {
          rowMappings.push({ type: "unknown" });
        }
      }

      rowMappings.push({ type: "evidence" });
      rowMappings.push({ type: "result" });
      rowMappings.push({ type: "comment" });
    }

    const attrRecord: Record<string, string> = {};
    attributes.forEach((attr) => {
      attrRecord[attr.id] = "";
    });

    let weekVal = "";
    let rawEvidenceVal = "";
    let rawResultVal = "";
    let rawCommentVal = "";

    cells.forEach((cell, cellIdx) => {
      if (cellIdx < rowMappings.length) {
        const mapping = rowMappings[cellIdx];
        const trimmed = (cell || "").trim();
        if (mapping.type === "week") {
          weekVal = trimmed;
        } else if (mapping.type === "evidence") {
          rawEvidenceVal = trimmed;
        } else if (mapping.type === "result") {
          rawResultVal = trimmed;
        } else if (mapping.type === "comment") {
          rawCommentVal = trimmed;
        } else if (mapping.type === "attribute") {
          let cleanVal = trimmed;
          if (/^pass$/i.test(trimmed)) {
            cleanVal = "Pass";
          } else if (/^fail$/i.test(trimmed)) {
            cleanVal = "Fail";
          }
          attrRecord[mapping.attributeId] = cleanVal;
        }
      }
    });

    if (
      weekVal === "" &&
      rawEvidenceVal === "" &&
      rawResultVal === "" &&
      rawCommentVal === "" &&
      Object.values(attrRecord).every((val) => val === "")
    ) {
      continue;
    }

    // Validate Result
    let cleanResultVal: "Pass" | "Fail" = "Pass";
    if (rawResultVal) {
      const resCheck = validateAndNormalizeResult(rawResultVal);
      if (resCheck.isValid) {
        cleanResultVal = resCheck.normalized;
      } else {
        rowWarnings.push(`Row ${i + 1} Result: '${rawResultVal}' is invalid, defaulted to 'Pass'`);
      }
    }

    // Validate Evidence
    let cleanEvidenceVal = "";
    if (rawEvidenceVal) {
      const eviCheck = validateAndNormalizeEvidence(rawEvidenceVal, evidenceOptions);
      if (eviCheck.isValid) {
        cleanEvidenceVal = eviCheck.normalized;
      } else {
        rowWarnings.push(`Row ${i + 1} Evidence: '${rawEvidenceVal}' is invalid file format`);
      }
    }

    newRowsData.push({
      week: weekVal,
      attributes: attrRecord,
      evidence: cleanEvidenceVal,
      result: cleanResultVal,
      comment: rawCommentVal,
    });
  }

  if (newRowsData.length > 0) {
    if (rowWarnings.length > 0) {
      return {
        newRowsToImport: newRowsData,
        overrideStartRowId: activeRowId !== null ? activeRowId : undefined,
        message: `Imported with warnings: ${rowWarnings.slice(0, 2).join("; ")}${rowWarnings.length > 2 ? ` (+${rowWarnings.length - 2} more)` : ""}`,
        severity: "warning",
      };
    }

    if (activeRowId !== null) {
      return {
        newRowsToImport: newRowsData,
        overrideStartRowId: activeRowId,
        message: `Successfully pasted and overrode ${newRowsData.length} row(s) starting from the selected row!`,
        severity: "success",
      };
    } else {
      return {
        newRowsToImport: newRowsData,
        message: `Successfully pasted and imported ${newRowsData.length} row(s) from Excel!`,
        severity: "success",
      };
    }
  } else {
    return {
      message: "No valid rows found to import from clipboard.",
      severity: "warning",
    };
  }
}